# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc42ef6c13783ed7c87659557eaadf2ab3818e0b8624301d6bea95262139b110eb21752a60b9417663ed234558935a1cfc9bc13fec735a17ccb0a5cb31f47850

test:
  secret_key_base: fc8f819d1ff3e17cfcb57aead1631b0f470f036cf525623acbc20dae1b5af89223d31401690392dcad43733b65ec631c950960cd93629a8b3da2d9246a457ee8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
